version: '3.5'
services:
  traefik:
    image: "traefik:v2.3"
    networks:
      - semapps
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=myEmail@myemail.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "D4t4-pl4yers"

  fuseki_compact:
    image: semapps/jena-fuseki-webacl:latest
    entrypoint: /docker-compact-entrypoint.sh
    profiles: 
      - compact
    volumes:
      - ./data/fuseki:/fuseki

  middleware:
    image: dataplayers/archipelago-middleware:0.1
    depends_on:
      - fuseki
      - keycloak
    volumes:
      - ./middleware/logs:/archipelago/middleware/logs
      - ./middleware/jwt:/archipelago/middleware/jwt
      - ./middleware/uploads:/archipelago/middleware/uploads
      - ../petr-peps/addOn:/archipelago/middleware/addOn
      - ./data/fuseki/databases/localData:/localData
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=D4t4-pl4yers
      - SEMAPPS_HOME_URL=https://data.petr-peps.data-players.com/
      - 'SEMAPPS_OIDC_ISSUER=http://keycloak:8080/auth/realms/DP/'
      - SEMAPPS_OIDC_CLIENT_ID=semapps
      - SEMAPPS_REDIS_URL=redis://redis:6379/0
      - SEMAPPS_BACKUP_SERVER_USER=dataplayers
      - SEMAPPS_BACKUP_SERVER_PASSWORD=D4t4Pl4yers
      - SEMAPPS_BACKUP_SERVER_HOST=dataplayers.exavault.com
      - SEMAPPS_BACKUP_SERVER_PATH=/backup/petr-peps/backups/
      - SEMAPPS_BACKUP_FUSEKI_DATASETS_PATH=/app/fuseki-backups/
    command: bash -c "cp -r ../petr-peps/addOn/middleware/* . && pm2-runtime 'yarn start'"
    networks:
      - semapps
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware.rule=Host(`data.petr-peps.data-players.com`)"
      - "traefik.http.routers.middleware.entrypoints=websecure"
      - "traefik.http.routers.middleware.tls.certresolver=myresolver"

  frontend:
    image:  dataplayers/archipelago-frontend:0.1
    environment:
      - REACT_APP_MIDDLEWARE_URL=https://data.petr-peps.data-players.com/
      - REACT_APP_MAPBOX_ACCESS_TOKEN=pk.eyJ1Ijoic3Jvc3NldDgxIiwiYSI6ImNrbDd0b2VkMzA1dDMycG9iemU4NnpuemsifQ.HvpZ3tnweVHEUYLb0tDvTg
      - PORT=4000
    volumes:
      - ../petr-peps/addOn:/archipelago/frontend/addOn
    networks:
      - semapps
    ports:
      - "4000:4000"
    command: bash -c "cp -r ../petr-peps/addOn/frontend/* . && yarn build && serve -s build -l 4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.petr-peps.data-players.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: myKeycloakPassword
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_FRONTEND_URL: 'https://login.petr-peps.data-players.com/auth'
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - './realm-export.json:/tmp/realm-export.json'
    ports:
      - '8080:8080'
    networks:
      - semapps
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`login.petr-peps.data-players.com`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"

  postgres:
    image: postgres
    volumes:
      - './keycloak/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - semapps

  redis:
    image: redis
    container_name: redis
    expose:
      - "6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - semapps
    command: ["redis-server", "--appendonly", "yes"]

networks:
  semapps:
    name: semapps_network